#!/bin/bash

function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

lines=("FexDroid By EmuTesting"
       ""
       "1) Start Fex"
       "2) Uninstall Fex"
       "0) Disconnect"
       ""
       "[CTRL+C] EXIT")

box_out_warning "${lines[@]}"

read option

if [ $option = 0 ] || [ $option = 1 ] || [ $option = 2 ] || [ $option = 3 ]

then

&>/dev/null

else

fex

fi

if [ $option = 1 ]
then

clear 

    if [ -d /data/data/com.termux/files/home/Fex ]
    then

        clear

        unset LD_PRELOAD

        export PATH=/sbin:/usr/bin:/usr/sbin:/system/bin:/system/xbin:$PATH

        export USER=root

        export HOME=/root

        export LANGUAGE=C

        export LANG=C

        folder=/data/data/com.termux/files/home/Fex
        
        sudo mount --bind /dev $folder/dev

        sudo mount --bind /sys $folder/sys

        sudo mount --bind /proc $folder/proc

        sudo mount --bind /dev/pts $folder/dev/pts

        sudo mount --bind /sdcard $folder/sdcard

        sudo touch /data/data/com.termux/files/home/Fex/opt/chroot
       
        termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null & sleep 1
	
        sudo mount --bind $PREFIX/tmp/.X11-unix $folder/tmp/.X11-unix

        sudo chroot $folder /bin/su - root

        echo -e "\033[1m\x1b[33m [ Unmounting dev/pts ... ]"

        sudo umount $folder/dev/pts

        echo -e " [ Unmounting /dev ... ]"

        sudo umount $folder/dev

        echo -e " [ Unmounting /proc ... ]"

        sudo umount $folder/proc

        echo -e " [ Unmounting sdcard ... ]"

        sudo umount $folder/sdcard

        echo -e " [ Unmounting /sys ... ]"

        sudo umount $folder/sys

        echo -e " \x1b[32m[ Unmounted ]\e[0m"

        exit 0

    else

        termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null & sleep 1 & sleep 1

        proot-distro login ubuntu --isolated --bind /sdcard:/sdcard --bind $PREFIX/tmp/.X11-unix:/tmp/.X11-unix

    fi

elif [ $option = 2 ]
then

        if [ -d ~/Fex ]
        then
                sudo rm -rf ~/Fex
                rm $PREFIX/bin/fex
        else
                proot-distro remove ubuntu &>/dev/null
                rm $PREFIX/bin/fex
        fi
fi


if [ $option = 0 ]
then

        exit 

fi
