#!/bin/bash

function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

clear

lines=("This script will change Wine version"
        "Select need Wine build:"
        "1) Stable"
        "2) Staging"
        "3) Staging-tkg"
        "4) Proton"
        "5) Wine GE"
        "6) Back to previous menu"
       "[CTRL+C] EXIT")

box_out_warning "${lines[@]}"
read build
cd /opt
if [ $build = 1 ]
then
	clear
        lines=("Select need Wine version:"
               "1) 7.5"
               "2) 7.20"
               "3) 8.0"
               "4) 8.5"
               "5) 8.13"
               "6) 8.15 (not working on Adreno 7xx/610)"
               "7) 8.16"
               "8) 8.17"
        "[CTRL+C] EXIT")

        box_out_warning "${lines[@]}"
        read ver
	if [ $ver = 1 ]
	then
		export ver=7.5
	elif [ $ver = 2 ]
	then
		export ver=7.20
	elif [ $ver = 3 ]
	then
		export ver=8.0
	elif [ $ver = 4 ]
	then
		export ver=8.5
	elif [ $ver = 5 ]
	then
		export ver=8.13
        elif [ $ver = 6 ]
	then
		export ver=8.15
        elif [ $ver = 7 ]
	then
		export ver=8.16
        elif [ $ver = 8 ]
	then
		export ver=8.17
	else
		box_out_failure "Incorrect Wine version"
		. /opt/Scripts/changewinever
	fi
        box_out_warning "Removing current Wine..."
        rm -r wine
       	box_out_warning "Removing current Wine prefix..."
	rm -r ~/.wine
        box_out_warning "Downloading and unpacking Wine Stable $ver..."
        wget https://github.com/Kron4ek/Wine-Builds/releases/download/$ver/wine-$ver-amd64.tar.xz -q
        tar -xf wine-$ver-amd64.tar.xz
        box_out_warning "Removing unpacked archive..."
        rm wine-$ver-amd64.tar.xz
        mv wine-$ver-amd64 wine
elif [ $build = 2 ]
then
	clear
	lines=("Select need Wine version:"
               "1) 7.5"
               "2) 7.20"
               "3) 8.0"
               "4) 8.5"
               "5) 8.13"
               "6) 8.15 (not working on Adreno 7xx/610)"
               "7) 8.16"
               "8) 8.17"
        "[CTRL+C] EXIT")

        box_out_warning "${lines[@]}"
        read ver
        if [ $ver = 1 ]
        then
                export ver=7.5
        elif [ $ver = 2 ]
        then
                export ver=7.20
        elif [ $ver = 3 ]
        then
                export ver=8.0
        elif [ $ver = 4 ]
        then
                export ver=8.5
        elif [ $ver = 5 ]
        then
                export ver=8.13
        elif [ $ver = 6 ]
	then
		export ver=8.15
        elif [ $ver = 7 ]
	then
		export ver=8.16
        elif [ $ver = 8 ]
	then
		export ver=8.17
	else
                box_out_failure "Incorrect Wine version"
                . /opt/Scripts/changewinever
        fi
        box_out_warning "Removing current Wine..."
        rm -r wine
        box_out_warning "Removing current Wine prefix..."
        rm -r ~/.wine
        box_out_warning "Downloading and unpacking Wine Staging $ver..."
        wget https://github.com/Kron4ek/Wine-Builds/releases/download/$ver/wine-$ver-staging-amd64.tar.xz -q
        tar -xf wine-$ver-staging-amd64.tar.xz
        box_out_warning "Removing unpacked archive..."
        rm wine-$ver-staging-amd64.tar.xz
        mv wine-$ver-staging-amd64 wine
elif [ $build = 3 ]
then
	clear
	lines=("Select need Wine version:"
               "1) 7.5"
               "2) 7.20"
               "3) 8.0"
               "4) 8.5"
               "5) 8.13"
               "6) 8.15 (not working on Adreno 7xx/610)"
               "7) 8.16"
               "8) 8.17"
        "[CTRL+C] EXIT")

        box_out_warning "${lines[@]}"
        read ver
        if [ $ver = 1 ]
        then
                export ver=7.5
        elif [ $ver = 2 ]
        then
                export ver=7.20
        elif [ $ver = 3 ]
        then
                export ver=8.0
        elif [ $ver = 4 ]
        then
                export ver=8.5
        elif [ $ver = 5 ]
        then
                export ver=8.13
        elif [ $ver = 6 ]
	then
		export ver=8.15
        elif [ $ver = 7 ]
	then
		export ver=8.16
        elif [ $ver = 8 ]
	then
		export ver=8.17
        else
                box_out_failure "Incorrect Wine version"
                . /opt/Scripts/changewinever
        fi
        box_out_warning "Removing current Wine..."
        rm -r wine
        box_out_warning "Removing current Wine prefix..."
        rm -r ~/.wine
        box_out_warning "Downloading and unpacking Wine Staging-tkg $ver..."
        wget https://github.com/Kron4ek/Wine-Builds/releases/download/$ver/wine-$ver-staging-tkg-amd64.tar.xz -q
        tar -xf wine-$ver-staging-tkg-amd64.tar.xz
        box_out_warning "Removing unpacked archive..."
        rm wine-$ver-staging-tkg-amd64.tar.xz
        mv wine-$ver-staging-tkg-amd64 wine
elif [ $build = 4 ]
then
        lines=("Select Proton version:"
               "1) 8.0-3"
               "2) Experimental 8.0"
               "3) 8.0-4"
        "[CTRL+C] EXIT")

        box_out_warning "${lines[@]}"
        read ver
        if [ $ver = 1 ]
        then
                export ver="8.0-3"
        elif [ $ver = 2 ]
        then
                export ver="exp-8.0"
        elif [ $ver = 3 ]
        then
                export ver="8.0-4"
        else
                box_out_failure "Incorrect Proton version"
                . /opt/Scripts/changewinever
        fi
	box_out_warning "Removing current Wine..."
	rm -r wine
	box_out_warning "Removing current Wine prefix..."
        rm -r ~/.wine
        box_out_warning "Downloading and unpacking Proton $ver..."
        wget https://github.com/Kron4ek/Wine-Builds/releases/download/proton-$ver/wine-proton-$ver-amd64.tar.xz -q
        tar -xf wine-proton-$ver-amd64.tar.xz
        box_out_warning "Removing unpacked archive..."
        rm wine-proton-$ver-amd64.tar.xz
        mv wine-proton-$ver-amd64 wine
elif [ $build = 5 ]
then
	clear
        lines=("Select need Wine-GE version:"
               "1) 8-13"
               "2) 8-14"
               "3) 8-15"
               "4) 8-16 (Not working, waiting for Box86 update)"
               "5) 8-17 (Not working, waiting for Box86 update)"
        "[CTRL+C] EXIT")

        box_out_warning "${lines[@]}"
        read ver
        if [ $ver = 1 ]
        then
                export ver=8-13
        elif [ $ver = 2 ]
        then
		export ver=8-14
        elif [ $ver = 3 ]
        then
		export ver=8-15
        elif [ $ver = 4 ]
        then
		export ver=8-16
        elif [ $ver = 5 ]
        then
		export ver=8-17
	else
                box_out_failure "Incorrect Wine-ge version"
                . /opt/Scripts/changewinever
        fi
	box_out_warning "Removing current Wine..."
        rm -r wine
        box_out_warning "Removing current Wine prefix..."
        rm -r ~/.wine
	box_out_warning "Downloading and unpacking Wine GE $ver..."
	wget https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton$ver/wine-lutris-GE-Proton$ver-x86_64.tar.xz -q
	tar -xf wine-lutris-GE-Proton$ver-x86_64.tar.xz
        box_out_warning "Removing unpacked archive..."
        rm wine-lutris-GE-Proton$ver-x86_64.tar.xz
        mv lutris-GE-Proton$ver-x86_64 wine
elif [ $build = 6 ]
then
        . /opt/Scripts/checkconfig
else
        box_out_failure "Incorrect Wine version"
        clear
        . /opt/Scripts/changewinever
fi
box_out_warning "Creating new Wine prefix..."
WINEDLLOVERRIDES=mscoree=d box64 wineboot &>/dev/null
box_out_warning "Installing DXVK 2.2, D8VK 1.0, vkd3d-proton 2.10..."
box64 wine64 z:/opt/Resources64/DXVK2.2/DXVK2.2.bat &>/dev/null
box_out_success "Done installing DXVK2.2"
cp /opt/Resources/D8VK1.0/d3d8.dll /root/.wine/drive_c/windows/syswow64/
box_out_success "Copied D8VK 1.0"
cp /opt/Resources/vkd3d-proton2.10/d3d12*.dll /root/.wine/drive_c/windows/syswow64/
box_out_success "Copied VKD3D 2.10 x64"
cp /opt/Resources64/vkd3d-proton2.10/d3d12*.dll /root/.wine/drive_c/windows/system32/
box_out_success "Copied VKD3D 2.10 x86"
box64 wine64 z:/opt/Resources64/OverrideDlls.bat &>/dev/null
box_out_warning "Copying shortucts..."
cp -r /opt/Shortcuts/* "/root/.wine/drive_c/ProgramData/Microsoft/Windows/Start Menu"
ln -s /sdcard/Download /root/.wine/dosdevices/d:
box_out_success "Wine version changed, back to start menu..."
. /opt/Scripts/checkconfig

