#!/bin/bash

if [ -e /opt/FexMoreNew ]
then
  rm -f /opt/FexMore
  mv /opt/FexMoreNew /opt/FexMore
fi

function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

clear


lines=("FexDroid By EmuTesting"
       ""
       "1) Start Fex"
       "2) Config Fex"
       "3) Run Winetricks"
	   ""
	   "8) More options"
       "0) Disconnect"
       ""
       "[CTRL+C] Terminal Mode")

box_out_warning "${lines[@]}"

read option
if [ $option = "1" ]
then

. /opt/Scripts/start-fex

elif [ $option = "2" ]
then

clear

FEXConfig

. /opt/Fex

elif [ $option = "3" ]
then

clear

FEXInterpreter /opt/wine/bin/wine64 winetricks
read

. /opt/Fex

elif [ $option = "8" ]
then

clear

. /opt/FexMore

elif [ $option = "0" ]
then

clear

sleep 2

exit
exit

else

clear

box_out_failure "INVALID OPTION"

sleep 2

. /opt/Fex

fi


read -p "" sair
case $sair in
	[1]* ) echo "";box64 wineserver -k &>/dev/null;echo"";echo"";echo "";exit
esac
