#!/bin/bash

clear

lines=("FexDroid By EmuTesting"
       ""
       "1) Start Fex"
       "2) Config Fex"
       "3) Run Winetricks"
	   ""
	   "8) More options"
       "0) Disconnect"
       ""
       "[CTRL+C] EXIT")

box_out_warning "${lines[@]}"

read option
if [ $option = "1" ]
then

. /opt/Scripts/start-fex

elif [ $option = "2" ]
then

clear

FEXConfig

. /opt/Fex

elif [ $option = "3" ]
then

clear

FEXInterpreter /opt/wine/bin/wine64 winetricks

. /opt/Fex

elif [ $option = "8" ]
then

clear

. /opt/FexMore

elif [ $option = "0" ]
then

clear

sleep 2

exit

else

clear

box_out_failure "INVALID OPTION"

sleep 2

. /opt/Fex

fi


read -p "" sair
case $sair in
	[1]* ) echo "";box64 wineserver -k &>/dev/null;echo"";echo"";echo "";exit
esac
