#!/bin/bash
function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

clear

lines=("1) Recreate Wine Prefix"
       "2) Change Wine ver"
       "3) About"
       "4) Update FexDroid Scripts"
       "5) Retry Building/Build GStreamer"
	     ""
	     "8) Back"
       "0) Disconnect"
       )

box_out_warning "${lines[@]}"

read option
if [ $option = "1" ]
then

clear

box_out_warning "RECREATING WINE PREFIX"

sleep 1

clear

box_out_warning "DELETING PREFIX"
rm -r ~/.wine

sleep 1

clear

box_out_warning "CREATING NEW PREFIX"

WINEDLLOVERRIDES=mscoree=d box64 wineboot &>/dev/null

sleep 1

clear

lines=("INSTALLING: "
       "DXVK 2.2"
       "D8VK 1.0"
	   "VKD3D 2.10"
       "")

box_out_success "${lines[@]}"

box64 wine z:/opt/Resources64/DXVK2.2/DXVK2.2.bat &>/dev/null
cp /opt/Resources/D8VK1.0/d3d8.dll /root/.wine/drive_c/windows/syswow64/
cp /opt/Resources/vkd3d-proton2.10/d3d12*.dll /root/.wine/drive_c/windows/syswow64/
cp /opt/Resources64/vkd3d-proton2.10/d3d12*.dll /root/.wine/drive_c/windows/system32/
box64 wine z:/opt/Resources64/OverrideDlls.bat &>/dev/null

sleep 1 

clear

box_out_warning "FINISHING"

cp -r /opt/Shortcuts/* "/root/.wine/drive_c/ProgramData/Microsoft/Windows/Start Menu"
ln -s /sdcard/Download /root/.wine/dosdevices/d:

sleep 1

clear

box_out_success "PREFIX CREATED SUCCESSFULLY"

. /opt/FexMore

elif [ $option = "2" ]
then

clear

. /opt/Scripts/changewinever
. /opt/FexMore

elif [ $option = "3" ]
then

clear

lines=("FEXDROID BY EMUTESTING"
       ""
       "Based on OpomboMORTO's FEX-android"
       "installation scripts"
       "Thanks to him for letting this public"
	     "and thanks to:"
       "Ilya from Box64Droid"
       "Olegos2 from Termux-box"
       "Mr. Purple for the constant support"
       "Everyone who support my channel"
       "and make shotouts to it"
       "And YOU for using it!"
       ""
       "If you wanna help my projects, you can go to"
       "patreon.com/EmuTesting"
       "and become a Patreon!"
       ""
       "Sincerely. GabiAle97"
       "")

box_out_success "${lines[@]}"

read -p "Press any key to continue: "

. /opt/FexMore

elif [ $option = "4" ]
then
  clear
  lines=("Updating FexDroid"
         ""
         "Please Wait"
         "")

  box_out_warning "${lines[@]}"
  cd /opt
  rm -f Fexconfig
  rm -f InstallFex
  rm -f Fex
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/Fexconfig && chmod +x Fexconfig
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/InstallFex && chmod +x InstallFex
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/Fex && chmod +x Fex
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/FexMore -O FexMoreNew && chmod +x FexMoreNew
  cd Scripts
  rm -f start-box64
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/start-fex && chmod +x start-fex
  rm -f checkconfig start
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/checkconfig && chmod +x checkconfig
  rm -f changewinever
  wget -q --no-cache https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/changewinever && chmod +x changewinever
  clear
  box_out_success "Update Completed"
  sleep 2
  . /opt/Fex
elif [ $option = "5" ]
then
  echo "Installing libgstreamer1.0-dev"
  mkdir temp-debs
  cd temp-debs
  wget -q http://ports.ubuntu.com/pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.22.2-1_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/gstreamer1.0/gir1.2-gstreamer-1.0_1.22.2-1_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glibc/libc6_2.35-0ubuntu3.4_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glibc/libc6-dev_2.35-0ubuntu3.4_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/e/elfutils/libdw-dev_0.188-2.1_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glib2.0/libglib2.0-0_2.76.4-0ubuntu1_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glib2.0/libglib2.0-dev_2.76.4-0ubuntu1_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/gstreamer1.0/libgstreamer1.0-0_1.22.2-1_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/libu/libunwind/libunwind-dev_1.6.2-3_armhf.deb
  wget -q http://ports.ubuntu.com/pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.22.2-1_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/g/gstreamer1.0/gir1.2-gstreamer-1.0_1.22.2-1_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glibc/libc6_2.35-0ubuntu3.4_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glibc/libc6-dev_2.35-0ubuntu3.4_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/e/elfutils/libdw-dev_0.188-2.1_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glib2.0/libglib2.0-0_2.76.4-0ubuntu1_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/g/glib2.0/libglib2.0-dev_2.76.4-0ubuntu1_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/g/gstreamer1.0/libgstreamer1.0-0_1.22.2-1_arm64.deb
  wget -q http://ports.ubuntu.com/pool/main/libu/libunwind/libunwind-dev_1.6.2-3_arm64.deb
  dpkg -i gir1.2-gstreamer-1.0_1.22.2-1_armhf.deb
  dpkg -i libc6_2.35-0ubuntu3.4_armhf.deb
  dpkg -i libc6-dev_2.35-0ubuntu3.4_armhf.deb
  dpkg -i libdw-dev_0.188-2.1_armhf.deb
  dpkg -i libglib2.0-0_2.76.4-0ubuntu1_armhf.deb
  dpkg -i libglib2.0-dev_2.76.4-0ubuntu1_armhf.deb
  dpkg -i libgstreamer1.0-0_1.22.2-1_armhf.deb
  dpkg -i libunwind-dev_1.6.2-3_armhf.deb
  dpkg -i libgstreamer1.0-dev_1.22.2-1_arm64.deb
  dpkg -i gir1.2-gstreamer-1.0_1.22.2-1_arm64.deb
  dpkg -i libc6_2.35-0ubuntu3.4_arm64.deb
  dpkg -i libc6-dev_2.35-0ubuntu3.4_arm64.deb
  dpkg -i libdw-dev_0.188-2.1_arm64.deb
  dpkg -i libglib2.0-0_2.76.4-0ubuntu1_arm64.deb
  dpkg -i libglib2.0-dev_2.76.4-0ubuntu1_arm64.deb
  dpkg -i libgstreamer1.0-0_1.22.2-1_arm64.deb
  dpkg -i libunwind-dev_1.6.2-3_arm64.deb
  dpkg -i libgstreamer1.0-dev_1.22.2-1_armhf.deb
  read
  . /opt/Fex

elif [ $option = "8" ]
then

clear

. /opt/Fex

elif [ $option = "0" ]
then
clear
exit
clear
exit

else

clear

box_out_failure "INVALID OPTION"

. /opt/FexMore

sleep 1

fi

read -p "" sair
case $sair in
           [1]* ) echo "";box64 wineserver -k &>/dev/null;echo"";echo"";echo ">
esac
