#!/bin/bash
function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

clear

lines=("1) Recreate Wine Prefix"
       "2) Change Wine ver"
       "3) About"
       "4) Update FexDroid"
	   ""
	   "8) Back"
       "0) Disconnect"
       ""
       "[CTRL+C] EXIT")

box_out_warning "${lines[@]}"

read option
if [ $option = "1" ]
then

clear

box_out_warning "RECREATING WINE PREFIX"

sleep 1

clear

box_out_warning "DELETING PREFIX"
rm -r ~/.wine

sleep 1

clear

box_out_warning "CREATING NEW PREFIX"

WINEDLLOVERRIDES=mscoree=d box64 wineboot &>/dev/null

sleep 1

clear

lines=("INSTALLING: "
       "DXVK 2.2"
       "D8VK 1.0"
	   "VKD3D 2.10"
       "")

box_out_success "${lines[@]}"

box64 wine z:/opt/Resources64/DXVK2.2/DXVK2.2.bat &>/dev/null
cp /opt/Resources/D8VK1.0/d3d8.dll /root/.wine/drive_c/windows/syswow64/
cp /opt/Resources/vkd3d-proton2.10/d3d12*.dll /root/.wine/drive_c/windows/syswow64/
cp /opt/Resources64/vkd3d-proton2.10/d3d12*.dll /root/.wine/drive_c/windows/system32/
box64 wine z:/opt/Resources64/OverrideDlls.bat &>/dev/null

sleep 1 

clear

box_out_warning "FINISHING"

cp -r /opt/Shortcuts/* "/root/.wine/drive_c/ProgramData/Microsoft/Windows/Start Menu"
ln -s /sdcard/Download /root/.wine/dosdevices/d:

sleep 1

clear

box_out_success "PREFIX CREATED SUCCESSFULLY"

. /opt/FexMore

elif [ $option = "2" ]
then

clear

. /opt/Scripts/changewinever
. /opt/FexMore

elif [ $option = "3" ]
then

clear

lines=("FEXDROID BY EMUTESTING"
       ""
       "Based on OpomboMORTO's FEX-android installation scripts"
       "Thanks to him for letting this public"
	   "and thanks to:"
       "Ilya from Box64Droid"
       "Olegos2 from Termux-box"
       "Mr. Purple for the constant support"
       "Everyone who support my channel and make shotouts to it"
       "And YOU for using it!"
       ""
       "If you wanna help my projects, you can go to"
       "patreon.com/EmuTesting"
       "and become a Patreon!"
       ""
       "Sincerely. GabiAle97"
       "")

box_out_success "${lines[@]}"

read -p "Press any key to continue: "

. /opt/FexMore

elif [ $option = "4" ]
then
  lines=("Updating FexDroid"
         ""
         "Please Wait"
         "")

  box_out_warning "${lines[@]}"
  if [ -e /opt/FexRootMode ]
  then
    cd Fex
    sudo wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/checkconfig && sudo chmod +x checkconfig
    sudo wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/Fexconfig && sudo chmod +x Fexconfig
    sudo wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/InstallFex && sudo chmod +x InstallFex
    sudo wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/Fex && sudo chmod +x Fex
    sudo wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/FexMore && sudo chmod +x FexMore
    sudo mv FexMore InstallFex Fex checkconfig Fexconfig /data/data/com.termux/files/home/Fex/opt
    sudo wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/start-fex && sudo chmod +x start-fex
    sudo mv start-fex /data/data/com.termux/files/home/Fex/opt/Scripts
    sudo rm -f /data/data/com.termux/files/home/Fex/opt/start
    sudo rm -f /data/data/com.termux/files/home/Fex/opt/Box64Droid.conf
    sudo rm -f /data/data/com.termux/files/home/Fex/opt/Scripts/start-box64
    cd $HOME

  else
  then
    cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/opt
    rm -f Fexconfig
    rm -f InstallFex
    rm -f Fex
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/Fexconfig && chmod +x Fexconfig
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/InstallFex && chmod +x InstallFex
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/Fex && chmod +x Fex
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/FexMore -O FexMoreNew && chmod +x FexMoreNew
    cd Scripts
    rm -f start-box64
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/start-fex && chmod +x start-fex
    rm -f checkconfig start
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/checkconfig && chmod +x checkconfig
    rm -f changewinever
    wget -q https://raw.githubusercontent.com/GabiAle97/FexDroid/main/Rootfs/Ubuntu/opt/changewinever && chmod +x changewinever
    cd $HOME
  fi
  box_out_success "Update Completed"
  sleep 2
  . /opt/Fex
elif [ $option = "8" ]
then

clear

. /opt/Fex

else

clear

box_out_failure "INVALID OPTION"

. /opt/FexMore

sleep 1

fi

read -p "" sair
case $sair in
           [1]* ) echo "";box64 wineserver -k &>/dev/null;echo"";echo"";echo ">
esac
