#!/bin/bash

function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

if [ -e /opt/newmeson ]
then
    wget -q http://launchpadlibrarian.net/683244912/meson_1.2.1-3_all.deb -O meson.deb
    dpkg -i meson.deb
    apt install -y libglib2.0-dev 
    apt install -y ffmpeg libavfilter-dev
    touch /opt/newmeson
fi

clear


box_out_warning "Installing gstreamer 1.22.6"


mkdir gstreamer
wget -q https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.22.6.tar.xz -O gstreamer.tar.xz 
tar -xJf gstreamer.tar.xz -C ./gstreamer 
rm gstreamer.tar.xz
cd gstreamer
cd $(ls)
mkdir build &&
cd    build &&

meson  setup ..            \
    --prefix=/usr       \
    --buildtype=release \
    -Dgst_debug=false   \
    -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
    -Dpackage-name="GStreamer 1.22.6 BLFS" &&
ninja
ninja install
cd /opt
read
clear

box_out_warning "Installing gst-plugins-base 1.22.6"
mkdir gst-plugins-base
wget -q https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.22.6.tar.xz -O gst-plugins-base.tar.xz 
tar -xJf gst-plugins-base.tar.xz -C ./gst-plugins-base 
rm gst-plugins-base.tar.xz
cd gst-plugins-base
cd $(ls)
mkdir build &&
cd    build &&

meson  setup ..               \
    --prefix=/usr          \
    --buildtype=release    \
    --wrap-mode=nodownload \
    -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
    -Dpackage-name="GStreamer 1.22.6 BLFS"    &&
ninja
ninja install
cd /opt
read
clear

box_out_warning "Installing gst-plugins-good-1.22.6"
mkdir gst-plugins-good-1.22.6
wget -q https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.22.6.tar.xz
tar -xJf gst-plugins-good-1.22.6.tar.xz -C ./gst-plugins-good-1.22.6
rm gst-plugins-good-1.22.6.tar.xz
cd gst-plugins-good-1.22.6
cd $(ls)
mkdir build &&
cd    build &&

meson setup ..            \
    --prefix=/usr       \
    --buildtype=release \
    -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
    -Dpackage-name="GStreamer 1.22.6 BLFS" &&
ninja
ninja install
cd /opt
read
clear

box_out_warning "Installing gst-plugins-bad-1.22.6"
mkdir gst-plugins-bad-1.22.6
wget -q https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.22.6.tar.xz
tar -xJf gst-plugins-bad-1.22.6.tar.xz -C ./gst-plugins-bad-1.22.6
rm gst-plugins-bad-1.22.6.tar.xz
cd gst-plugins-bad-1.22.6
cd $(ls)
mkdir build &&
cd    build &&

meson  setup ..            \
    --prefix=/usr       \
    --buildtype=release \
    -Dgpl=enabled       \
    -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
    -Dpackage-name="GStreamer 1.22.6 BLFS" &&
ninja
ninja install
cd /opt
read
clear

box_out_warning "Installing gst-plugins-ugly-1.22.6"
mkdir gst-plugins-ugly-1.22.6
wget -q https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.22.6.tar.xz
tar -xJf gst-plugins-ugly-1.22.6.tar.xz -C ./gst-plugins-ugly-1.22.6
rm gst-plugins-ugly-1.22.6.tar.xz
cd gst-plugins-ugly-1.22.6
cd $(ls)
mkdir build &&
cd    build &&

meson  setup ..            \
    --prefix=/usr       \
    --buildtype=release \
    -Dgpl=enabled       \
    -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
    -Dpackage-name="GStreamer 1.22.6 BLFS" &&
ninja
ninja install
cd /opt
read
clear

box_out_warning "Installing gst-libav-1.22.6"
mkdir gst-libav-1.22.6
wget -q https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.22.6.tar.xz
tar -xJf gst-libav-1.22.6.tar.xz -C ./gst-libav-1.22.6
rm gst-libav-1.22.6.tar.xz
cd gst-libav-1.22.6
cd $(ls)
mkdir build &&
cd    build &&

meson  setup ..            \
    --prefix=/usr       \
    --buildtype=release \
    -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
    -Dpackage-name="GStreamer 1.22.6 BLFS" &&
ninja
ninja install
cd /opt
read
clear