#!/bin/bash
mkdir gstreamer
wget -q https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.22.6.tar.xz -O gstreamer.tar.xz &>/dev/null
tar -xJf gstreamer.tar.xz -C ./gstreamer &>/dev/null
wget -q http://launchpadlibrarian.net/683244912/meson_1.2.1-3_all.deb -O meson.deb
dpkg -i meson.deb
cd gstreamer
mkdir build &&
cd    build &&

meson  setup ..            \
       --prefix=/usr       \
       --buildtype=release \
       -Dgst_debug=false   \
       -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
       -Dpackage-name="GStreamer 1.22.6 BLFS" &&
ninja
ninja install