#!/bin/bash

function box_out_success() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 2
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 2)" "-$w" "$l" "$(tput setaf 2)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_warning() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 3
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 3)" "-$w" "$l" "$(tput setaf 3)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}

function box_out_failure() {
  local s=("$@") b w

  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done

  tput setaf 1
  echo " -${b//?/-}-"
  echo "| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 1)" "-$w" "$l" "$(tput setaf 1)"
  done

  echo "| ${b//?/ } |"
  echo " -${b//?/-}-"
  tput sgr 0
}
wget -q http://launchpadlibrarian.net/683244912/meson_1.2.1-3_all.deb -O meson.deb
dpkg -i meson.deb

clear

lines=("Select libraries to install: "
       ""
       "1) gstreamer"
       "2) gst-plugins-base"
       "3) gst-libav"
       "")

box_out_success "${lines[@]}"
read libselect

if [ $libselect = "1" ]
then

    box_out_warning "Installing gstreamer 1.22.6"

    apt install -y libglib2.0-dev 
    mkdir gstreamer
    wget -q https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.22.6.tar.xz -O gstreamer.tar.xz 
    tar -xJf gstreamer.tar.xz -C ./gstreamer 
    cd gstreamer
    cd $(ls)
    mkdir build &&
    cd    build &&

    meson  setup ..            \
        --prefix=/usr       \
        --buildtype=release \
        -Dgst_debug=false   \
        -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
        -Dpackage-name="GStreamer 1.22.6 BLFS" &&
    ninja
    ninja install
    cd /opt/Script
    read
    clear
fi

if [ $libselect = "2" ]
then
    box_out_warning "Installing gst-plugins-base 1.22.6"
    mkdir gst-plugins-base
    wget -q https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.22.6.tar.xz -O gst-plugins-base.tar.xz 
    tar -xJf gst-plugins-base.tar.xz -C ./gst-plugins-base 
    cd gst-plugins-base
    cd $(ls)
    mkdir build &&
    cd    build &&

    meson  setup ..               \
        --prefix=/usr          \
        --buildtype=release    \
        --wrap-mode=nodownload \
        -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
        -Dpackage-name="GStreamer 1.22.6 BLFS"    &&
    ninja
    ninja install
    cd /opt/Script
    read
    clear
fi

if [ $libselect = "3" ]
then
    apt install -y ffmpeg
    box_out_warning "Installing gst-libav-1.22.6"
    mkdir gst-libav-1.22.6
    wget -q https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.22.6.tar.xz
    tar -xJf gst-libav-1.22.6.tar.xz -C ./gst-libav-1.22.6
    cd gst-libav-1.22.6
    cd $(ls)
    mkdir build &&
    cd    build &&

    meson  setup ..            \
        --prefix=/usr       \
        --buildtype=release \
        -Dpackage-origin=https://www.linuxfromscratch.org/blfs/view/svn/ \
        -Dpackage-name="GStreamer 1.22.6 BLFS" &&
    ninja
    ninja install
    cd /opt/Script
    read
    clear
fi