#!/bin/bash

clear

lines=("Select need resoultion:"
       "1) 800x600 (4:3)"
       "2) 1024x768 (4:3)"
       "3) 1280x720 (16:9)"
       "4) 1920x1080 (16:9)"
       "5) Custom resolution"
       "6) Back to previous menu"
       ""
       "[CTRL+C] EXIT")

box_out_warning "${lines[@]}"

read res
clear

if [ $res = 1 ]
then
	export resolution_fex="800x600"
elif [ $res = 2 ]
then
	export resolution_fex="1024x768"
elif [ $res = 3 ]
then
	export resolution_fex="1280x720"
elif [ $res = 4 ]
then
	export resolution_fex="1920x1080"
elif [ $res = 5 ]
then
	echo "Which resolution you want to use? (e.g. 2304x941)"
	read res
	if [ -z $res ]
		then
		echo "Empty resolution!"
		. /opt/Scripts/start-fex
	else
		clear
	fi
elif [ $res = 6 ]
then
	. /opt/Scripts/checkconfig
else
        echo "Incorrect resolution"
        . /opt/Scripts/start-fex
fi

box_out_success "SELECTED RESOLUTION: $resolution_fex"

WINEDEBUG=-all DXVK_HUD=fps,gpuload,version taskset -c 4-7 box64 wine64 explorer /desktop=shell,$resolution_fex /opt/TFM & FEXInterpreter /opt/wine/bin/wine64 explorer /desktop=shell,$resolution_fex

read -p "" sair
case $sair in
        [1]* ) echo "";box64 wineserver -k &>/dev/null;echo"";echo "";echo "";exit
esac
 
